DROP ALL OBJECTS;

SET MODE Oracle;

CREATE SEQUENCE id_seq
    INCREMENT BY 10
    START WITH 1000
    MINVALUE 1000
    MAXVALUE 100000
    CYCLE
    CACHE 2;


CREATE TABLE drone(
    drone_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    serial varchar(100) not null,
    weight number not null,
    model varchar(100) not null,
    battery number not null,
    state varchar(30) not null,
    created_at date default sysdate,
    PRIMARY KEY(drone_id)
);


CREATE TABLE medication(
	med_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	name  varchar (200) not null,
	weight number not null,
	code varchar(500) not null,
	image varchar2 not null,
	created_at date default sysdate,
	drone_id NUMBER NOT NULL,
	PRIMARY KEY (med_id),
	FOREIGN KEY(drone_id) REFERENCES drone(drone_id)

);


CREATE TABLE droneBatteryLog(
	log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	drone_id number NOT NULL,
	battery number NOT NULL,
	created_at date default sysdate,
	PRIMARY KEY (log_id),
	FOREIGN KEY(drone_id) REFERENCES drone(drone_id)
);

