DROP ALL OBJECTS;

SET MODE Oracle;

CREATE TABLE drones(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) not null,
    weight number not null,
    serial varchar(100) not null,
    model varchar(100) not null,
    PRIMARY KEY(id)
);


INSERT INTO drones(name,weight,serial,model) values('Drone 1',300.30,'495994KKKJ09IK','LightWeigth');